import { booleanField, fileUploadField, genderField, gstField, numericField, requiredNumberField, requiredStringField, stringAlphanumeric, stringAlphanumericWithSpecialChars, stringDateFormat, stringEmail, stringMobileNumber, stringNumeric, stringOnlyAlphabets, stringPassword } from "./baseSchema";
type TransFn = (key: string, params?: Record<string, unknown>) => string;

export const appUserTestValidate = (t: TransFn) => ({
	id: stringNumeric(t('appUserTests.columns.fields.id'), t, 0, 0),
	name: stringOnlyAlphabets(t('appUserTests.columns.fields.name'), t, 2, 100),
	firstName: stringOnlyAlphabets(t('appUserTests.columns.fields.firstName'), t, 2, 100),
	lastName: stringOnlyAlphabets(t('appUserTests.columns.fields.lastName'), t, 2, 100),
	mobile: stringMobileNumber(t('appUserTests.columns.fields.mobile'), t, 10, 10),
	mobileVerified: booleanField(t('appUserTests.columns.fields.mobileVerified'), t),
	emailId: stringEmail(t('appUserTests.columns.fields.emailId'), t, 5, 100),
	emailVerified: booleanField(t('appUserTests.columns.fields.emailVerified'), t),
	shopName: stringOnlyAlphabets(t('appUserTests.columns.fields.shopName'), t, 2, 200),
	password: stringPassword(t('appUserTests.columns.fields.password'), t, 2, 100),
	pincode: numericField(t('appUserTests.columns.fields.pincode'), t, 6, 6),
	state: stringAlphanumeric(t('appUserTests.columns.fields.state'), t, 1, 100),
	district: stringAlphanumeric(t('appUserTests.columns.fields.district'), t, 1, 100),
	address: stringAlphanumericWithSpecialChars(t('appUserTests.columns.fields.address'), t, 2, 10000),
	addressLine: stringAlphanumericWithSpecialChars(t('appUserTests.columns.fields.addressLine'), t, 2, 10000),
	verifyShop: requiredStringField(t('appUserTests.columns.fields.verifyShop'), t, 2, 100),
	verifyShopLabel: requiredStringField(t('appUserTests.columns.fields.verifyShopLabel'), t, 2, 100),
	gst: gstField(t('appUserTests.columns.fields.gst'), t, 15, 15),
	gstCertificate: fileUploadField(t('appUserTests.columns.fields.gstCertificate'), t, 1, 2),
	photoShopFront: fileUploadField(t('appUserTests.columns.fields.photoShopFront'), t, 1, 2),
	visitingCard: fileUploadField(t('appUserTests.columns.fields.visitingCard'), t, 1, 2),
	cheque: fileUploadField(t('appUserTests.columns.fields.cheque'), t, 1, 2),
	gstOtp: stringAlphanumeric(t('appUserTests.columns.fields.gstOtp'), t, 6, 6),
	isActive: booleanField(t('appUserTests.columns.fields.isActive'), t),
	isAdmin: booleanField(t('appUserTests.columns.fields.isAdmin'), t),
	hasImpersonateAccess: booleanField(t('appUserTests.columns.fields.hasImpersonateAccess'), t),
	photoAttachment: fileUploadField(t('appUserTests.columns.fields.photoAttachment'), t, 1, 2),
	role: requiredStringField(t('appUserTests.columns.fields.role'), t, 2, 100),
	roleLabel: requiredStringField(t('appUserTests.columns.fields.roleLabel'), t, 2, 100),
	publish: requiredStringField(t('appUserTests.columns.fields.publish'), t, 2, 100),
	publishLabel: requiredStringField(t('appUserTests.columns.fields.publishLabel'), t, 2, 100),
	importDataId: stringNumeric(t('appUserTests.columns.fields.importDataId'), t, 0, 0),
	lastLogin: stringDateFormat(t('appUserTests.columns.fields.lastLogin'), t),
	defaultLanguage: stringOnlyAlphabets(t('appUserTests.columns.fields.defaultLanguage'), t, 2, 10),
	isPremiumUser: booleanField(t('appUserTests.columns.fields.isPremiumUser'), t),
	totalPlot: stringNumeric(t('appUserTests.columns.fields.totalPlot'), t, 1, 100),
	reportedTo: requiredStringField(t('appUserTests.columns.fields.reportedTo'), t, 2, 100),
	reportedToName: requiredStringField(t('appUserTests.columns.fields.reportedToName'), t, 2, 100),
	reportedBy: requiredNumberField(t('appUserTests.columns.fields.reportedBy'), t),
	reportedByName: requiredNumberField(t('appUserTests.columns.fields.reportedByName'), t),
	gender: genderField(t('appUserTests.columns.fields.gender'), t),
	genderLabel: genderField(t('appUserTests.columns.fields.genderLabel'), t),
	createDate: stringDateFormat(t('appUserTests.columns.fields.createDate'), t),
	updateDate: stringDateFormat(t('appUserTests.columns.fields.updateDate'), t),
	deleteDate: stringDateFormat(t('appUserTests.columns.fields.deleteDate'), t),
	createById: stringNumeric(t('appUserTests.columns.fields.createById'), t, 0, 0),
	updateById: stringNumeric(t('appUserTests.columns.fields.updateById'), t, 0, 0),
	deleteById: stringNumeric(t('appUserTests.columns.fields.deleteById'), t, 0, 0),
	isDelete: booleanField(t('appUserTests.columns.fields.isDelete'), t),

	// <!--validate-Data-->
});