import {
  anyValueField,
  booleanField,
  checkboxField,
  fileUploadField,
  genderField,
  numberOrDoubleField,
  // numericField,
  requiredStringField,
  stringDateFormat,
  stringEmail,
  stringMobileNumber,
  stringNumeric,
} from './baseSchema';
type TransFn = (key: string, params?: Record<string, unknown>) => string;
export const jobRequestValidate = (t: TransFn) => ({
  id: stringNumeric(t('jobRequests.columns.fields.id'), t, 0, 0),
  name: anyValueField(t('jobRequests.columns.fields.name'), t, 2, 100),
  firstName: anyValueField(
    t('jobRequests.columns.fields.firstName'),
    t,
    2,
    100,
  ),
  lastName: anyValueField(t('jobRequests.columns.fields.lastName'), t, 2, 100),
  mobile: stringMobileNumber(t('jobRequests.columns.fields.mobile'), t, 10, 10),
  emailId: stringEmail(t('jobRequests.columns.fields.emailId'), t, 5, 100),
  dob: stringDateFormat(t('jobRequests.columns.fields.dob'), t),
  gender: genderField(t('jobRequests.columns.fields.gender'), t),
  qualification: anyValueField(
    t('jobRequests.columns.fields.qualification'),
    t,
    2,
    100,
  ),
  curCtc: numberOrDoubleField(t('jobRequests.columns.fields.curCtc'), t),
  expCtc: numberOrDoubleField(t('jobRequests.columns.fields.expCtc'), t),
  noticePeriod: anyValueField(
    t('jobRequests.columns.fields.noticePeriod'),
    t,
    1,
    100,
  ),
  designation: anyValueField(
    t('jobRequests.columns.fields.designation'),
    t,
    1,
    200,
  ),
  experience: anyValueField(
    t('jobRequests.columns.fields.experience'),
    t,
    1,
    200,
  ),
  currentWorkLocation: anyValueField(
    t('jobRequests.columns.fields.currentWorkLocation'),
    t,
    1,
    300,
  ),
  preferredLocation: anyValueField(
    t('jobRequests.columns.fields.preferredLocation'),
    t,
    1,
    300,
  ),
  employmentType: genderField(
    t('jobRequests.columns.fields.employmentType'),
    t,
  ),
  jobCategoryId: requiredStringField(
    t('jobRequests.columns.fields.jobCategoryId'),
    t,
    1,
    100,
  ),
  jobCategoryIdName: requiredStringField(
    t('jobRequests.columns.fields.jobCategoryIdName'),
    t,
    1,
    100,
  ),
  applyingPost: requiredStringField(
    t('jobRequests.columns.fields.applyingPost'),
    t,
    1,
    200,
  ),
  skillSet: anyValueField(t('jobRequests.columns.fields.skillSet'), t, 1, 200),
  howDidKnow: genderField(t('jobRequests.columns.fields.howDidKnow'), t),
  didKnowNiran: genderField(t('jobRequests.columns.fields.didKnowNiran'), t),
  ifYes: anyValueField(t('jobRequests.columns.fields.ifYes'), t, 1, 300),
  fileDoc: fileUploadField(t('jobRequests.columns.fields.fileDoc'), t, 1, 10),
  isAccept: checkboxField(t('jobRequests.columns.fields.isAccept'), t),
  createDate: stringDateFormat(t('jobRequests.columns.fields.createDate'), t),
  updateDate: stringDateFormat(t('jobRequests.columns.fields.updateDate'), t),
  deleteDate: stringDateFormat(t('jobRequests.columns.fields.deleteDate'), t),
  createById: stringNumeric(
    t('jobRequests.columns.fields.createById'),
    t,
    0,
    0,
  ),
  updateById: stringNumeric(
    t('jobRequests.columns.fields.updateById'),
    t,
    0,
    0,
  ),
  deleteById: stringNumeric(
    t('jobRequests.columns.fields.deleteById'),
    t,
    0,
    0,
  ),
  isDelete: booleanField(t('jobRequests.columns.fields.isDelete'), t),

  // <!--validate-Data-->
});
